export const SET_APP_CONFIG = 'SET_APP_CONFIG';
export const SET_APP_CONFIG_UI_FLAGS = 'SET_APP_CONFIG_UI_FLAGS';
export const SET_CONVERSATION_ATTRIBUTES = 'SET_CONVERSATION_ATTRIBUTES';
export const UPDATE_CONVERSATION_ATTRIBUTES = 'UPDATE_CONVERSATION_ATTRIBUTES';
export const CLEAR_CONVERSATION_ATTRIBUTES = 'CLEAR_CONVERSATION_ATTRIBUTES';
